import {
  Document, Page, Text, View, StyleSheet,
} from '@react-pdf/renderer';
import type { ProgramBudgetLine, DonorSpendLine } from '@/lib/services/organization-finance.service';

/**
 * PDF rendering for the two organization-axis reports (Phase 5 gap analysis
 * item 1). Reuses the same react-pdf primitives and visual language as
 * components/pdf/contribution-receipt.tsx — that file (and share-certificate
 * .tsx) is the ONLY existing precedent for @react-pdf/renderer in this
 * codebase; lib/services/report-email.service.ts does not itself render
 * PDFs, it only emails pre-built attachments, so there was no "PDF service"
 * to extend — this mirrors the actual rendering pattern instead (a
 * components/pdf/*.tsx component rendered via renderToBuffer at the call
 * site, here the export job handler in lib/jobs/handlers.ts).
 */

function fmt(n: number) {
  return new Intl.NumberFormat('en-KE', {
    style: 'currency', currency: 'KES', maximumFractionDigits: 2,
  }).format(n);
}

function fmtDate(iso: string | null) {
  if (!iso) return 'N/A';
  try {
    return new Date(iso).toLocaleDateString('en-KE', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch {
    return iso;
  }
}

const styles = StyleSheet.create({
  page:       { padding: 36, fontSize: 9, fontFamily: 'Helvetica', color: '#1f2937' },
  header:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  orgName:    { fontSize: 16, fontFamily: 'Helvetica-Bold', color: '#085041' },
  subtitle:   { fontSize: 10, color: '#6b7280', marginTop: 2 },
  badge:      { fontSize: 8, color: '#1D9E75', fontFamily: 'Helvetica-Bold', textTransform: 'uppercase', letterSpacing: 1 },
  table:      { marginTop: 8 },
  tHeadRow:   { flexDirection: 'row', backgroundColor: '#E1F5EE', paddingVertical: 5, paddingHorizontal: 4 },
  tRow:       { flexDirection: 'row', paddingVertical: 4, paddingHorizontal: 4, borderBottomWidth: 0.5, borderBottomColor: '#e5e7eb', borderBottomStyle: 'solid' },
  tHeadCell:  { fontFamily: 'Helvetica-Bold', fontSize: 8, color: '#085041' },
  tCell:      { fontSize: 8 },
  colName:    { flexGrow: 2, flexBasis: 0 },
  colNum:     { flexGrow: 1, flexBasis: 0, textAlign: 'right' },
  colSmall:   { flexGrow: 0.7, flexBasis: 0, textAlign: 'right' },
  sectionHdr: { fontSize: 11, fontFamily: 'Helvetica-Bold', color: '#085041', marginTop: 14, marginBottom: 4 },
  footer:     { position: 'absolute', bottom: 24, left: 36, right: 36, fontSize: 8, color: '#9ca3af', textAlign: 'center' },
});

export interface OrganizationReportPdfProps {
  organizationName: string;
  generatedAt:      string; // ISO
}

export function ProgramBudgetReportPdf(
  props: OrganizationReportPdfProps & { lines: ProgramBudgetLine[] },
) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.orgName}>{props.organizationName}</Text>
            <Text style={styles.subtitle}>Program Budget &amp; Utilization Report</Text>
          </View>
          <Text style={styles.badge}>Generated {fmtDate(props.generatedAt)}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tHeadRow} fixed>
            <Text style={[styles.tHeadCell, styles.colName]}>Program</Text>
            <Text style={[styles.tHeadCell, styles.colSmall]}>Status</Text>
            <Text style={[styles.tHeadCell, styles.colNum]}>Budget</Text>
            <Text style={[styles.tHeadCell, styles.colNum]}>Disbursed</Text>
            <Text style={[styles.tHeadCell, styles.colNum]}>Reserved</Text>
            <Text style={[styles.tHeadCell, styles.colNum]}>Remaining</Text>
            <Text style={[styles.tHeadCell, styles.colSmall]}>Util. %</Text>
            <Text style={[styles.tHeadCell, styles.colSmall]}>Variance</Text>
          </View>
          {props.lines.map((l) => (
            <View style={styles.tRow} key={l.id} wrap={false}>
              <Text style={[styles.tCell, styles.colName]}>{l.name}</Text>
              <Text style={[styles.tCell, styles.colSmall]}>{l.status}</Text>
              <Text style={[styles.tCell, styles.colNum]}>{fmt(l.budget)}</Text>
              <Text style={[styles.tCell, styles.colNum]}>{fmt(l.disbursed)}</Text>
              <Text style={[styles.tCell, styles.colNum]}>{fmt(l.reserved)}</Text>
              <Text style={[styles.tCell, styles.colNum]}>{fmt(l.remaining)}</Text>
              <Text style={[styles.tCell, styles.colSmall]}>{l.utilizationPct.toFixed(1)}%</Text>
              <Text style={[styles.tCell, styles.colSmall]}>
                {l.variancePct === null ? 'N/A' : `${l.variancePct.toFixed(1)}%`}
              </Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer} fixed>
          Generated by Kitabu Yetu · {props.lines.length} program(s) · This is a system-generated report.
        </Text>
      </Page>
    </Document>
  );
}

export function DonorSpendReportPdf(
  props: OrganizationReportPdfProps & { lines: DonorSpendLine[] },
) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.orgName}>{props.organizationName}</Text>
            <Text style={styles.subtitle}>Donor / Grant Spend Report</Text>
          </View>
          <Text style={styles.badge}>Generated {fmtDate(props.generatedAt)}</Text>
        </View>

        {props.lines.map((d) => (
          <View key={d.fundingSource} wrap={false}>
            <Text style={styles.sectionHdr}>
              {d.fundingSource} — {d.programCount} program(s) — {d.utilizationPct.toFixed(1)}% utilized
            </Text>
            <View style={styles.table}>
              <View style={styles.tHeadRow}>
                <Text style={[styles.tHeadCell, styles.colName]}>Program</Text>
                <Text style={[styles.tHeadCell, styles.colNum]}>Budget</Text>
                <Text style={[styles.tHeadCell, styles.colNum]}>Disbursed</Text>
              </View>
              {d.programs.map((p) => (
                <View style={styles.tRow} key={p.id}>
                  <Text style={[styles.tCell, styles.colName]}>{p.name}</Text>
                  <Text style={[styles.tCell, styles.colNum]}>{fmt(p.budget)}</Text>
                  <Text style={[styles.tCell, styles.colNum]}>{fmt(p.disbursed)}</Text>
                </View>
              ))}
              <View style={[styles.tRow, { backgroundColor: '#f9fafb' }]}>
                <Text style={[styles.tCell, styles.colName, { fontFamily: 'Helvetica-Bold' }]}>Total</Text>
                <Text style={[styles.tCell, styles.colNum, { fontFamily: 'Helvetica-Bold' }]}>{fmt(d.totalBudget)}</Text>
                <Text style={[styles.tCell, styles.colNum, { fontFamily: 'Helvetica-Bold' }]}>{fmt(d.totalDisbursed)}</Text>
              </View>
            </View>

            {d.byGroup.length > 0 && (
              <View style={[styles.table, { marginTop: 4 }]}>
                <View style={styles.tHeadRow}>
                  <Text style={[styles.tHeadCell, styles.colName]}>Recipient group</Text>
                  <Text style={[styles.tHeadCell, styles.colNum]}>Settled amount</Text>
                </View>
                {d.byGroup.map((g, i) => (
                  <View style={styles.tRow} key={`${g.groupId}-${i}`}>
                    <Text style={[styles.tCell, styles.colName]}>{g.groupName ?? 'Unknown group'}</Text>
                    <Text style={[styles.tCell, styles.colNum]}>{fmt(g.amount)}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by Kitabu Yetu · {props.lines.length} funding source(s) · This is a system-generated report.
        </Text>
      </Page>
    </Document>
  );
}
